# Generated by Django 4.0.5 on 2022-06-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_departamentomodel_delete_departamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamentomodel',
            options={'ordering': ['name'], 'verbose_name': 'deparment', 'verbose_name_plural': 'deparments'},
        ),
    ]
