# Generated by Django 4.0.5 on 2022-06-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_habilidadesmodel_alter_personamodel_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HabilidadesModel',
            new_name='HabilidadModel',
        ),
        migrations.AddField(
            model_name='personamodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
        migrations.AddField(
            model_name='personamodel',
            name='habilidad',
            field=models.ManyToManyField(to='persona.habilidadmodel'),
        ),
    ]
