# Generated by Django 4.0.5 on 2022-06-22 23:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_rename_habilidadesmodel_habilidadmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personamodel',
            name='cv',
            field=ckeditor.fields.RichTextField(default='ninguno'),
            preserve_default=False,
        ),
    ]
