# Generated by Django 4.0.5 on 2022-06-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_personamodel_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='personamodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nombre Completo'),
        ),
    ]
